### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by Andrew-liu** [davecheney/httpstat#69]
When I use installation command, I failed.

```
$ go get -u github.com/davecheney/httpstat                                                                                   [10:56:20]
# github.com/davecheney/httpstat
failed MSpanList_Insert 0x7925c0 0xeb13f9b6bae5 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x2a3330, 0x10)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90
runtime.(*mSpanList).insert(0x3a68a8, 0x7925c0)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:933 +0x293
runtime.(*mheap).freeSpanLocked(0x3a60a0, 0x7925c0, 0x100, 0x0)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:809 +0x4be
runtime.(*mheap).grow(0x3a60a0, 0x30, 0x0)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:675 +0x2a0
runtime.(*mheap).allocSpanLocked(0x3a60a0, 0x30, 0x4c2fb20)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:553 +0x4e3
runtime.(*mheap).alloc_m(0x3a60a0, 0x30, 0x100000000, 0x7924d0)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbfe910)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3a60a0, 0x30, 0x100000000, 0xc820022000)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x60000, 0xc800000003, 0x4d2d0)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0x39f700)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:245 fp=0xc824a3b508 sp=0xc824a3b500
runtime.mallocgc(0x60000, 0x0, 0xc800000003, 0x8)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:665 +0x9eb fp=0xc824a3b5e0 sp=0xc824a3b508
runtime.rawmem(0x60000, 0x2f)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:809 +0x32 fp=0xc824a3b608 sp=0xc824a3b5e0
runtime.growslice(0x1e80a0, 0xc824ccc000, 0x4c000, 0x4c000, 0x4c001, 0x0, 0x0, 0x0)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/slice.go:95 +0x233 fp=0xc824a3b678 sp=0xc824a3b608
cmd/link/internal/ld.Symgrow(0xc820082240, 0xc824a10fc0, 0x4c002)
       	/usr/local/Cellar/go/1.6/libexec/src/cmd/link/internal/ld/data.go:52 +0x26e fp=0xc824a3b730 sp=0xc824a3b678
cmd/link/internal/ld.addpctab(0xc824a10fc0, 0xc80004bfbc, 0xc820ecc030, 0x4bfbc)
       	/usr/local/Cellar/go/1.6/libexec/src/cmd/link/internal/ld/pcln.go:130 +0x6a fp=0xc824a3b7b0 sp=0xc824a3b730
cmd/link/internal/ld.pclntab()
       	/usr/local/Cellar/go/1.6/libexec/src/cmd/link/internal/ld/pcln.go:323 +0x8d1 fp=0xc824a3b9e0 sp=0xc824a3b7b0
cmd/link/internal/ld.Ldmain()
       	/usr/local/Cellar/go/1.6/libexec/src/cmd/link/internal/ld/pobj.go:241 +0x1f33 fp=0xc824a3be60 sp=0xc824a3b9e0
cmd/link/internal/amd64.Main()
       	/usr/local/Cellar/go/1.6/libexec/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc824a3be68 sp=0xc824a3be60
main.main()
       	/usr/local/Cellar/go/1.6/libexec/src/cmd/link/main.go:27 +0x36f fp=0xc824a3bf40 sp=0xc824a3be68
runtime.main()
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc824a3bf90 sp=0xc824a3bf40
runtime.goexit()
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc824a3bf98 sp=0xc824a3bf90
```

I install `go` using homebrew 

```
$ go version                                                                                                                 [22:45:15]
go version go1.6 darwin/amd64
```

**Comment by moorereason** [comment]
Looks like you're on macOS 10.12 Sierra.  You need to upgrade to Go 1.7 or later.

**Comment by FalcoSuessgott** [comment]
When I try to install httpstat, I receive this error.

**go get -u github.com/davecheney/httpstat**
`cd .; git clone https://github.com/davecheney/httpstat /root/projects/src/src/github.com/davecheney/httpstat
Cloning into '/root/projects/src/src/github.com/davecheney/httpstat'...
fatal: unable to access 'https://github.com/davecheney/httpstat/': Peer's Certificate issuer is not recognized.
package github.com/davecheney/httpstat: exit status 128
`
**go version**
`go version go1.7 linux/amd64
`
Any help ?

**Comment by davecheney** [comment]
What heppens if you run that git clone command manually? That will rule out
the go installation.

Check which version of git you have installed, if homebrew has installed
something overriding the xcode version it may not be able to correctly
resolve ssl certificates

**Comment by Andrew-liu** [comment]
When I upgrade go into `version 1.7.1` on macOS 10.12 Sierra, I fix this question. Thanks. @moorereason @davecheney 

```
$ sw_vers                                                                                                                       [8:54:46]
ProductName:	Mac OS X
ProductVersion:	10.12

$ go version                                                                                                                    [8:53:13]
go version go1.7.1 darwin/amd64
```

**but, What a pity.**

```
$ httpstat https://example.com/                                                                                       [8:58:43]
zsh: command not found: httpstat
```

**Comment by davecheney** [comment]
Is $GOPATH/bin in your $PATH?

**Comment by Andrew-liu** [comment]
I have set env variable for golang in `~/.zshrc`

```
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOROOT/bin
```

**Comment by llitfkitfk** [comment]
@Andrew-liu export GOBIN="$GOPATH/bin"

**Comment by davecheney** [comment]
`go install` or `go get` (which calls `go install` on the source it just cloned) will place the binary in `$GOPATH/bin`. To make your life easy, you should place that location in your `$PATH`.

**Comment by davecheney** [comment]
I'm going to close this issue now as there is no httpstat bug to address. Thank you.
